## makeCacheMatrix: receives a square matrix "x" and caches its inverse 
## It produces a list where $get_mat (get the matrix "x"), 
##                          $get_inv (get the inverse of "x")

makeCacheMatrix <- function(x = matrix()) {

   inv <- solve(x)
   
   get_mat <- function() x           # Get the value of matrix "x"
   get_inv <- function()  inv        # Get the cached inverse of "x"

   list(get_inv=get_inv,get_mat=get_mat)
   
}

## cacheSolve: receives a special list (generated by makeCacheMatrix) and get the matrix inverse
## from the cached data. Otherwise, it calculates the inverse.

cacheSolve <- function(x, ...){
  
  inv <- x$get_inv()
  
  if(!is.null(inv)){
    message("Getting cached inverse!")
    return(inv)
  }
  
  inv2 <- solve(x$get_mat())
  inv2
 
}
